# Generated by Django 4.2 on 2025-12-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlshortner',
            old_name='original_url',
            new_name='url',
        ),
    ]
